import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ReactNode} from "react";
import Index from "@/components/providers";
import Header from "@/components/Header";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Index>
            <Header/>
            <main className={"px-4 md:px-16 lg:px-32 h-full"}>
                {children}
            </main>
        </Index>
        </body>
        </html>
    )
}
